# Generated by Django 4.2 on 2025-03-10 09:26

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('price_range', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_notification_enabled', models.BooleanField(default=False)),
                ('pay_day', models.IntegerField(default=app.models.InvestmentPlan.default_pay_day)),
                ('investment_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_plans', to='app.investmentidea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='app.investmentplan')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('recepient', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('investment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.investmentplan')),
            ],
        ),
    ]
