# Generated by Django 4.2 on 2025-03-11 07:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_investmentidea_investmentplan_saving_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentidea',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
