# Generated by Django 4.2 on 2025-03-13 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_investmentidea_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
