# Generated by Django 4.2 on 2025-03-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_saving_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='notification_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
